name: nsmp_barcode_app
description: Embebed web application for printing barcodes in Naumen SMP & ITSM 365
version: 1.0.1
#homepage: https://www.example.com
#author: mdemyanov <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#  dart_barcode: ^1.0.0
  naumen_smp_jsapi: ^1.0.0

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0
